export interface ConnecteurConfig {
  id: string;
  name: string;
  description: string;
  category: "identification" | "pieces" | "lubrifiants" | "diffusion" | "garanties" | "atelier" | "financement" | "logistique" | "controle" | "assurance";
  authType: "token" | "login_password";
  color: string;
  siteUrl: string;
  docsUrl: string;
  features: string[];
  requiresSubscription: boolean;
  icon?: string;
}

export interface ConnecteurCredentials {
  id?: string;
  connecteur_id: string;
  enabled: boolean;
  token?: string;
  login?: string;
  password?: string;
}

export const CATEGORY_LABELS: Record<string, string> = {
  identification: "Identification véhicule",
  pieces: "Pièces détachées",
  lubrifiants: "Lubrifiants",
  diffusion: "Diffusion annonces",
  garanties: "Garanties",
  atelier: "Gestion atelier",
  financement: "Financement & Crédit",
  logistique: "Logistique & Transport",
  controle: "Contrôle technique",
  assurance: "Assurance",
};

export const CONNECTEURS: ConnecteurConfig[] = [
  // === IDENTIFICATION ===
  {
    id: "api_plaque",
    name: "API Plaque Immatriculation",
    description: "Identification complète d'un véhicule à partir de sa plaque (VIN, marque, modèle, version, énergie, etc.)",
    category: "identification",
    authType: "token",
    color: "bg-blue-600",
    siteUrl: "https://www.apiplaqueimmatriculation.com",
    docsUrl: "https://www.apiplaqueimmatriculation.com/documentation",
    features: ["Recherche par plaque SIV", "Plaques FNI anciennes", "Plaques étrangères EU", "Décodage VIN", "Données techniques complètes", "K-Type TecDoc"],
    requiresSubscription: true,
  },
  {
    id: "siv_ants",
    name: "SIV / ANTS",
    description: "Système d'Immatriculation des Véhicules — interrogation officielle du fichier national.",
    category: "identification",
    authType: "login_password",
    color: "bg-indigo-600",
    siteUrl: "https://immatriculation.ants.gouv.fr",
    docsUrl: "https://immatriculation.ants.gouv.fr",
    features: ["Vérification immatriculation", "Historique véhicule", "Situation administrative"],
    requiresSubscription: true,
  },
  {
    id: "histovec",
    name: "HistoVec",
    description: "Historique officiel du véhicule fourni par le Ministère de l'Intérieur (sinistres, km, propriétaires).",
    category: "identification",
    authType: "token",
    color: "bg-blue-800",
    siteUrl: "https://histovec.interieur.gouv.fr",
    docsUrl: "https://histovec.interieur.gouv.fr",
    features: ["Historique sinistres", "Kilométrage certifié", "Nombre de propriétaires", "Rapport officiel"],
    requiresSubscription: false,
  },
  {
    id: "vin_decoder",
    name: "VIN Decoder (NHTSA)",
    description: "Décodage du numéro VIN pour obtenir les spécifications constructeur (mondial).",
    category: "identification",
    authType: "token",
    color: "bg-slate-600",
    siteUrl: "https://vpic.nhtsa.dot.gov",
    docsUrl: "https://vpic.nhtsa.dot.gov/api/",
    features: ["Décodage VIN mondial", "Specs constructeur", "Rappels sécurité", "API gratuite"],
    requiresSubscription: false,
  },

  // === PIÈCES DÉTACHÉES ===
  {
    id: "tecdoc",
    name: "TecDoc",
    description: "Catalogue international de pièces détachées automobiles (TecAlliance).",
    category: "pieces",
    authType: "token",
    color: "bg-orange-600",
    siteUrl: "https://www.tecalliance.net",
    docsUrl: "https://webservice.tecalliance.net/pegasus-3-0/info",
    features: ["Catalogue pièces", "Références croisées", "Recherche par K-Type", "Illustrations techniques"],
    requiresSubscription: true,
  },
  {
    id: "dasir",
    name: "DASIR / TecAlliance",
    description: "Base de données techniques et pièces détachées du marché français.",
    category: "pieces",
    authType: "login_password",
    color: "bg-amber-600",
    siteUrl: "https://www.tecalliance.net",
    docsUrl: "https://www.tecalliance.net",
    features: ["Données techniques FR", "Pièces de rechange", "Équivalences"],
    requiresSubscription: true,
  },
  {
    id: "partslink24",
    name: "Partslink24",
    description: "Catalogue de pièces d'origine constructeur (OEM) avec schémas éclatés.",
    category: "pieces",
    authType: "login_password",
    color: "bg-teal-600",
    siteUrl: "https://www.partslink24.com",
    docsUrl: "https://www.partslink24.com",
    features: ["Pièces OEM", "Schémas éclatés", "Références constructeur"],
    requiresSubscription: true,
  },
  {
    id: "pavi",
    name: "PAVI",
    description: "Plateforme d'aide à la vente et à l'identification de pièces auto.",
    category: "pieces",
    authType: "login_password",
    color: "bg-cyan-600",
    siteUrl: "https://www.pavi.fr",
    docsUrl: "https://www.pavi.fr",
    features: ["Identification pièces", "Tarification", "Commande en ligne"],
    requiresSubscription: true,
  },
  {
    id: "oscaro_pro",
    name: "Oscaro Pro",
    description: "Catalogue et commande de pièces détachées pour professionnels.",
    category: "pieces",
    authType: "login_password",
    color: "bg-sky-600",
    siteUrl: "https://www.oscaro.com",
    docsUrl: "https://www.oscaro.com/pro",
    features: ["Catalogue pièces", "Tarifs pro", "Livraison express", "Retours simplifiés"],
    requiresSubscription: false,
  },
  {
    id: "autodoc_pro",
    name: "Autodoc Pro",
    description: "Plateforme européenne de commande de pièces auto pour professionnels.",
    category: "pieces",
    authType: "login_password",
    color: "bg-emerald-600",
    siteUrl: "https://www.autodoc.fr",
    docsUrl: "https://www.autodoc.fr",
    features: ["Pièces multimarques", "Prix compétitifs", "Livraison EU", "API catalogue"],
    requiresSubscription: false,
  },

  // === LUBRIFIANTS ===
  {
    id: "yacco",
    name: "Yacco",
    description: "Préconisations lubrifiants et huiles moteur par véhicule.",
    category: "lubrifiants",
    authType: "login_password",
    color: "bg-red-600",
    siteUrl: "https://www.yacco.com",
    docsUrl: "https://www.yacco.com/preconisations",
    features: ["Préconisations huile", "Catalogue produits", "Fiches techniques"],
    requiresSubscription: false,
  },
  {
    id: "total_lubrifiants",
    name: "TotalEnergies Lubrifiants",
    description: "Préconisations et catalogue lubrifiants TotalEnergies pour professionnels.",
    category: "lubrifiants",
    authType: "login_password",
    color: "bg-red-500",
    siteUrl: "https://lubricants.totalenergies.com",
    docsUrl: "https://lubricants.totalenergies.com",
    features: ["Préconisations huile", "Catalogue Quartz/Rubia", "Fiches de sécurité"],
    requiresSubscription: false,
  },

  // === GESTION ATELIER ===
  {
    id: "vroomly",
    name: "Vroomly",
    description: "Plateforme de gestion atelier, devis et prise de rendez-vous en ligne.",
    category: "atelier",
    authType: "login_password",
    color: "bg-green-600",
    siteUrl: "https://www.vroomly.com",
    docsUrl: "https://www.vroomly.com",
    features: ["Gestion atelier", "Devis en ligne", "Rendez-vous", "Facturation"],
    requiresSubscription: true,
  },
  {
    id: "mecaplanning",
    name: "MecaPlanning",
    description: "Logiciel de planification atelier et gestion des interventions mécaniques.",
    category: "atelier",
    authType: "login_password",
    color: "bg-lime-600",
    siteUrl: "https://www.mecaplanning.com",
    docsUrl: "https://www.mecaplanning.com",
    features: ["Planning atelier", "OR numérique", "Suivi temps", "Facturation"],
    requiresSubscription: true,
  },

  // === DIFFUSION ANNONCES ===
  {
    id: "leboncoin",
    name: "Leboncoin",
    description: "Diffusion automatique de vos annonces véhicules sur Leboncoin.",
    category: "diffusion",
    authType: "login_password",
    color: "bg-orange-500",
    siteUrl: "https://www.leboncoin.fr",
    docsUrl: "https://www.leboncoin.fr",
    features: ["Publication annonces", "Synchronisation stock", "Gestion statuts"],
    requiresSubscription: true,
  },
  {
    id: "autoscout24",
    name: "AutoScout24",
    description: "Diffusion de vos annonces sur AutoScout24, leader européen.",
    category: "diffusion",
    authType: "login_password",
    color: "bg-yellow-500",
    siteUrl: "https://www.autoscout24.fr",
    docsUrl: "https://www.autoscout24.fr",
    features: ["Publication annonces", "Audience européenne", "Statistiques vues"],
    requiresSubscription: true,
  },
  {
    id: "lacentrale",
    name: "LaCentrale",
    description: "Diffusion sur LaCentrale, référence du marché VO en France.",
    category: "diffusion",
    authType: "login_password",
    color: "bg-blue-500",
    siteUrl: "https://www.lacentrale.fr",
    docsUrl: "https://www.lacentrale.fr",
    features: ["Publication annonces", "Côte véhicule", "Visibilité nationale"],
    requiresSubscription: true,
  },
  {
    id: "paruvendu",
    name: "ParuVendu",
    description: "Diffusion d'annonces véhicules sur ParuVendu Auto.",
    category: "diffusion",
    authType: "login_password",
    color: "bg-rose-500",
    siteUrl: "https://www.paruvendu.fr",
    docsUrl: "https://www.paruvendu.fr",
    features: ["Publication annonces", "Audience nationale", "Gestion multi-annonces"],
    requiresSubscription: true,
  },
  {
    id: "facebook_marketplace",
    name: "Facebook Marketplace",
    description: "Publication automatique sur Facebook Marketplace et pages professionnelles.",
    category: "diffusion",
    authType: "token",
    color: "bg-blue-700",
    siteUrl: "https://www.facebook.com/marketplace",
    docsUrl: "https://developers.facebook.com/docs/marketing-apis",
    features: ["Publication automatique", "Audience locale", "Ciblage géographique", "Intégration page pro"],
    requiresSubscription: false,
  },

  // === GARANTIES ===
  {
    id: "ams",
    name: "AMS Garantie",
    description: "Garanties mécaniques pour véhicules d'occasion (9 formules disponibles).",
    category: "garanties",
    authType: "login_password",
    color: "bg-purple-600",
    siteUrl: "https://www.ams-garantie.com",
    docsUrl: "https://www.ams-garantie.com",
    features: ["9 formules garantie", "Tarifs par véhicule", "PDF conditions", "Attestation en ligne"],
    requiresSubscription: true,
  },
  {
    id: "opteven",
    name: "Opteven",
    description: "Solutions de garantie panne mécanique et assistance pour véhicules d'occasion.",
    category: "garanties",
    authType: "login_password",
    color: "bg-violet-600",
    siteUrl: "https://www.opteven.com",
    docsUrl: "https://www.opteven.com",
    features: ["Garantie panne mécanique", "Assistance 24/7", "Réseau réparateurs agréés", "Gestion en ligne"],
    requiresSubscription: true,
  },
  {
    id: "icare",
    name: "iCare by GPA",
    description: "Garanties constructeur étendues et garanties VO multimarques.",
    category: "garanties",
    authType: "login_password",
    color: "bg-fuchsia-600",
    siteUrl: "https://www.gpa.fr",
    docsUrl: "https://www.gpa.fr",
    features: ["Garantie constructeur étendue", "Garantie VO", "Interface pro", "Certificat en ligne"],
    requiresSubscription: true,
  },

  // === FINANCEMENT ===
  {
    id: "cetelem",
    name: "Cetelem (BNP Paribas)",
    description: "Solutions de financement auto et crédit pour particuliers via votre concession.",
    category: "financement",
    authType: "login_password",
    color: "bg-green-700",
    siteUrl: "https://www.cetelem.fr",
    docsUrl: "https://www.cetelem.fr/professionnels",
    features: ["Crédit auto", "LOA / LLD", "Simulation en ligne", "Dossier dématérialisé"],
    requiresSubscription: true,
  },
  {
    id: "cofidis",
    name: "Cofidis",
    description: "Crédit auto et financement pour professionnels de l'automobile.",
    category: "financement",
    authType: "login_password",
    color: "bg-yellow-600",
    siteUrl: "https://www.cofidis.fr",
    docsUrl: "https://www.cofidis.fr/professionnels",
    features: ["Crédit classique", "LOA", "Scoring instantané", "API partenaire"],
    requiresSubscription: true,
  },

  // === LOGISTIQUE ===
  {
    id: "allo_trans_auto",
    name: "AlloTransAuto",
    description: "Transport de véhicules par camion plateau entre professionnels.",
    category: "logistique",
    authType: "login_password",
    color: "bg-gray-600",
    siteUrl: "https://www.allotransauto.com",
    docsUrl: "https://www.allotransauto.com",
    features: ["Devis transport", "Suivi livraison", "Plateau / remorque", "France entière"],
    requiresSubscription: false,
  },

  // === CONTRÔLE TECHNIQUE ===
  {
    id: "utac_otc",
    name: "UTAC OTC",
    description: "Accès aux données de contrôle technique et résultats OTC (Organisme Technique Central).",
    category: "controle",
    authType: "login_password",
    color: "bg-stone-600",
    siteUrl: "https://www.utac-otc.com",
    docsUrl: "https://www.utac-otc.com",
    features: ["Résultats CT", "Historique contrôles", "Points de contrôle", "Contre-visite"],
    requiresSubscription: true,
  },

  // === ASSURANCE ===
  {
    id: "assurance_pro",
    name: "Assurance Garage Pro",
    description: "Assurance tous risques garage, responsabilité civile pro et couverture stock.",
    category: "assurance",
    authType: "login_password",
    color: "bg-pink-600",
    siteUrl: "https://www.ffsa.fr",
    docsUrl: "https://www.ffsa.fr",
    features: ["RC Pro garage", "Assurance stock", "Garantie essai route", "Couverture incendie/vol"],
    requiresSubscription: true,
  },
];
